In [ ]:
import pandas as pd

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving arxiv_ai_ml_papers.csv to arxiv_ai_ml_papers.csv

In [ ]:
df = pd.read_csv(list(uploaded.keys())[0])

In [ ]:
df.sample(5)

,paper_id,title,authors,num_authors,first_author,abstract,abstract_length,word_count,primary_category,all_categories,...,journal_ref,comment,has_doi,doi,arxiv_url,pdf_url,is_large_collaboration,is_updated,update_lag_days,days_since_submission
2286,2604.20601v1,Self-Guided Plan Extraction for Instruction-Fo...,Zoya Volovikova; Nikita Sorokin; Dmitriy Lukas...,5,Zoya Volovikova,"We introduce SuperIgor, a framework for instru...",816,115,cs.AI,cs.AI; cs.CL,...,Not Available,No comment,0,Not Available,https://arxiv.org/abs/2604.20601v1,https://arxiv.org/pdf/2604.20601v1,0,0,0,8
5335,2604.09162v2,Persona-E: A Human-Grounded Dataset for Person...,Yuqin Yang; Haowu Zhou; Haoran Tu; Zhiwen Hui;...,10,Yuqin Yang,Most affective computing research treats emoti...,1117,147,cs.CL,cs.CL; cs.AI; cs.HC,...,Not Available,Accepted by ACL 2026 Main,0,Not Available,https://arxiv.org/abs/2604.09162v2,https://arxiv.org/pdf/2604.09162v2,0,1,8,20
4141,2604.16270v1,"From Benchmarking to Reasoning: A Dual-Aspect,...",Van-Truong Le,1,Van-Truong Le,The complexity of Vietnam's legal texts presen...,1484,205,cs.CL,cs.CL; cs.AI,...,Not Available,"7 pages, 2 figures. Accepted at the FISU Joint...",0,Not Available,https://arxiv.org/abs/2604.16270v1,https://arxiv.org/pdf/2604.16270v1,0,0,0,13
6509,2603.18104v4,"Adaptive Domain Models: Bayesian Evolution, Wa...",Houston Haynes,1,Houston Haynes,Prevailing AI training infrastructure assumes ...,1892,232,cs.AI,cs.AI; cs.DC; cs.LG; cs.NE,...,Not Available,"32 pages, 3 figures",0,Not Available,https://arxiv.org/abs/2603.18104v4,https://arxiv.org/pdf/2603.18104v4,0,1,32,43
3097,2604.17930v1,Heterogeneity in Formal Linguistic Competence ...,H S V N S Kowndinya Renduchintala; Sumit Bhatia,2,H S V N S Kowndinya Renduchintala,Large Language Models (LLMs) exhibit a puzzlin...,1646,219,cs.CL,cs.CL; cs.AI; cs.LG,...,Not Available,ACL'26 (Findings),0,Not Available,https://arxiv.org/abs/2604.17930v1,https://arxiv.org/pdf/2604.17930v1,0,0,0,10

Warning: Total number of columns (26) exceeds max_columns (20) limiting to first (20) columns.

In [ ]:
df.columns

Index(['paper_id', 'title', 'authors', 'num_authors', 'first_author',
       'abstract', 'abstract_length', 'word_count', 'primary_category',
       'all_categories', 'num_categories', 'submitted_date', 'updated_date',
       'year', 'month', 'has_journal_ref', 'journal_ref', 'comment', 'has_doi',
       'doi', 'arxiv_url', 'pdf_url', 'is_large_collaboration', 'is_updated',
       'update_lag_days', 'days_since_submission'],
      dtype='object')

In [ ]:
def to_paper(row):
  return f"""PAPER ID : {row['paper_id']}

  Title : {row['title']}

  Authors : {row['authors']}

  Abstract : {row['abstract']}

  Primary Category : {row['primary_category']}

  All Categories : {row['all_categories']}"""

In [ ]:
to_paper(df.loc[1])

"PAPER ID : 2604.26231v1\n\n  Title : ProMax: Exploring the Potential of LLM-derived Profiles with Distribution Shaping for Recommender Systems\n\n  Authors : Yi Zhang; Yiwen Zhang; Kai Zheng; Tong Chen; Hongzhi Yin\n\n  Abstract : The remarkable text understanding and generation capabilities of large language models (LLMs) have revitalized the field of general recommendation based on implicit user feedback. Rather than deploying LLMs directly as recommendation models, a more flexible paradigm leverages their ability to interpret users' historical interactions and semantic contexts to extract structured profiles that characterize user preferences. These profiles can be further transformed into actionable high-dimensional representations, serving as powerful signals to augment and strengthen recommendation models. However, the mechanism by which such profiles enhance recommendation performance within the feature space remains insufficiently understood. Moreover, existing studies predominantly rely on nonlinear alignment and fusion strategies to incorporate these profiles, which often lead to semantic loss and fail to fully exploit their potential. To address these limitations, we revisit profiles from a retrieval perspective and propose a simple yet effective recommendation framework built upon distribution shaping (ProMax) in this paper. We begin by employing dense retrieval to uncover the collaborative relationships between user and item profiles within the feature space. Based on this insight, we introduce a dual distribution-reshaping process, in which the profile distribution acts as a guiding signal to steer the recommendation model toward learning user preferences for unseen items beyond the scope of observed interactions. We apply ProMax to four classic recommendation methods on three public datasets. The results indicate that ProMax substantially improves base model performance and outperforms existing LLM-based recommendation approaches.\n\n  Primary Category : cs.IR\n\n  All Categories : cs.IR"

In [ ]:
df['document'] = df.apply(to_paper, axis=1)

In [ ]:
df.sample(1)

,paper_id,title,authors,num_authors,first_author,abstract,abstract_length,word_count,primary_category,all_categories,...,comment,has_doi,doi,arxiv_url,pdf_url,is_large_collaboration,is_updated,update_lag_days,days_since_submission,document
208,2604.26237v1,Apriori-based Analysis of Learned Helplessness...,John Paul P. Miranda,1,John Paul P. Miranda,This study applied the Apriori algorithm to an...,1338,177,cs.AI,cs.AI; cs.CY; cs.ET; cs.LG,...,"9 pages, 2 figures, 1 table, journal article",1,10.34190/ejel.24.2.4602,https://arxiv.org/abs/2604.26237v1,https://arxiv.org/pdf/2604.26237v1,0,0,0,1,PAPER ID : 2604.26237v1\n\n Title : Apriori-b...

In [ ]:
df.loc[208,'document']

'PAPER ID : 2604.26237v1\n\n  Title : Apriori-based Analysis of Learned Helplessness in Mathematics Tutoring: Behavioral Patterns by Level, Intervention, and Outcome\n\n  Authors : John Paul P. Miranda\n\n  Abstract : This study applied the Apriori algorithm to analyze behavioral interaction patterns associated with learned helplessness (LH) in mathematics tutoring system logs. Interaction data were examined across three dimensions: LH level (low vs. high), system-based intervention (with vs. without), and problem-solving outcomes (solved vs. unsolved). The analysis of the complete dataset showed that skipping problems without using hints was the most frequent pattern linked to unsolved outcomes, while persistence behaviors such as not skipping were less dominant overall. Comparisons by LH level showed that low-LH students had stronger links between problem solving and not skipping, as well as positive associations between hint use and solved outcomes. High-LH students showed more avoidance patterns, with skipping strongly tied to unsolved outcomes. In the comparison of system-based intervention conditions, students without intervention had the highest lift for persistence-success links, while the with-intervention group had stronger patterns involving skipping behaviors leading to unsolved outcomes. Outcome-specific analysis showed that not skipping was consistently associated with solved problems across all groups, while skipping without hints predicted unsolved outcomes. Practical implications and recommendations are discussed.\n\n  Primary Category : cs.AI\n\n  All Categories : cs.AI; cs.CY; cs.ET; cs.LG'

In [38]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("BAAI/bge-small-en-v1.5")

embedding = model.encode(df.loc[208,'document'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/94.8k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/743 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/133M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/711k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [39]:
embedding

array([-5.13966642e-02,  4.38412018e-02, -3.14437039e-02,  2.68022623e-02,
       -4.05562818e-02, -1.41176465e-03,  3.36868539e-02,  8.54258426e-03,
        3.35702933e-02, -1.49657475e-02,  9.50845610e-03,  1.63158309e-03,
        4.16555703e-02,  2.51905099e-02, -9.15410835e-03, -3.13424296e-03,
       -3.49254347e-02,  7.50091076e-02, -3.30339298e-02,  2.26745801e-03,
        1.29457824e-02,  3.29060433e-03, -1.20369066e-02, -3.60304043e-02,
       -8.03743955e-03,  5.54322675e-02, -2.07304955e-02, -8.18673819e-02,
       -6.72350032e-03, -1.83607146e-01, -2.90194736e-03,  3.78988460e-02,
        6.53080419e-02,  1.38583384e-03, -5.94212934e-02,  6.69016540e-02,
       -4.40827198e-02,  4.29331586e-02, -1.10501321e-02, -2.61894278e-02,
        7.19391415e-03,  2.47366633e-02, -1.35283871e-03, -2.03361213e-02,
       -2.78342552e-02, -2.59191915e-02, -3.35047320e-02, -3.65088321e-02,
       -2.68421490e-02, -4.38103378e-02, -5.57515658e-02, -4.48038876e-02,
        1.91794503e-02,  4.96697091e-02,  8.74854682e-04,  2.03473866e-02,
        6.82793036e-02,  1.38698667e-02, -2.02808958e-02,  6.65367022e-02,
        7.34642595e-02,  4.81615998e-02, -1.47976547e-01,  5.98011240e-02,
        4.49100956e-02,  3.65941040e-02, -2.85957567e-02, -1.77536141e-02,
        2.29872297e-02,  3.42867412e-02, -2.08740626e-02,  1.33166583e-02,
        2.13644989e-02,  7.92895183e-02,  8.69527236e-02,  3.31431553e-02,
        1.28891198e-02, -4.92169298e-02,  5.60832210e-02, -1.75751057e-02,
        5.68022765e-02,  4.75353329e-03, -4.09504920e-02, -7.21285259e-03,
       -1.75662141e-03, -4.40795012e-02, -5.63293742e-03, -5.47782965e-02,
        3.83026488e-02, -2.80991253e-02,  3.90987145e-03, -1.35490196e-02,
       -3.12910788e-02,  4.78231907e-03,  2.13879626e-02, -6.60796314e-02,
       -4.91001969e-03, -2.72839740e-02, -7.62249529e-02,  3.93629253e-01,
       -2.45991312e-02, -4.03058343e-03,  6.02588756e-03,  2.14713439e-02,
        3.35566583e-04, -7.51887262e-02,  4.06231955e-02, -6.49927258e-02,
       -4.21623476e-02,  5.09546092e-03, -9.11459234e-03, -2.14661825e-02,
        7.13034794e-02, -2.40702853e-02, -3.02939881e-02,  1.10947657e-02,
        1.91028137e-02,  3.23059522e-02,  3.53050642e-02,  2.31139641e-02,
        1.25086904e-02,  2.64612399e-02,  3.46333906e-02, -3.54862511e-02,
       -7.03055551e-03, -5.17795011e-02, -5.52827045e-02,  5.86781688e-02,
        7.76305934e-03, -4.21086326e-02,  8.51171985e-02, -3.61009166e-02,
       -9.04135853e-02,  9.14162770e-03,  7.38771772e-03,  1.21790841e-02,
        4.16508541e-02,  1.53614003e-02, -2.23546736e-02,  2.02675145e-02,
        2.60930527e-02,  1.13837207e-02,  3.79039124e-02, -3.73606421e-02,
       -8.78777876e-02,  1.31653100e-01,  4.45020525e-03,  3.98906320e-03,
        6.38846587e-03,  2.10473891e-02,  1.20581063e-02, -1.34954648e-02,
       -8.27066079e-02, -2.46010032e-02, -1.53955920e-02,  2.30293609e-02,
        2.47809235e-02,  1.72194671e-02, -3.67266461e-02,  3.03001143e-02,
       -5.04284538e-02, -4.99967225e-02, -3.81521620e-02,  2.93119233e-02,
        5.90813980e-02, -2.85461396e-02, -8.72535165e-03,  6.90037897e-03,
       -6.28948212e-02, -4.20674495e-02,  6.35084286e-02,  2.33317036e-02,
       -1.74672268e-02, -1.84040312e-02, -1.21636959e-02,  2.12298855e-02,
        1.55168558e-02, -4.35880795e-02,  1.35947978e-02,  6.65646568e-02,
        4.41918671e-02, -6.38943762e-02,  1.57240853e-02,  4.24367189e-02,
       -3.23217772e-02, -5.70121780e-03,  3.26866060e-02, -2.26465352e-02,
       -8.00957158e-03, -4.74204682e-02, -4.78459224e-02, -6.54027835e-02,
       -9.41051319e-02, -5.62752038e-03, -3.11658476e-02, -2.31418014e-03,
        8.05533212e-03, -5.18785715e-02, -3.59904543e-02,  4.52002361e-02,
       -1.77124105e-02,  5.26991077e-02, -8.92523862e-03,  1.16708260e-02,
        3.51856835e-02,  5.19790351e-02,  5.53399436e-02, -3.09521668e-02,
        8.13322216e-02,  2.69063320e-02, -5.45626245e-02, -2.39799768e-02,
        1.53706362e-02, -3.93786095e-03,  1.49072306e-02,  2.91501693e-02,
        4.23540995e-02,  2.86341030e-02, -3.33949439e-02,  1.67050473e-02,
       -5.11960452e-03, -8.13446287e-03, -8.21190700e-03, -3.18571866e-01,
       -7.29502887e-02,  1.09196641e-02, -1.83161478e-02, -1.59599222e-02,
       -4.93217930e-02,  4.52349074e-02, -6.51306100e-03, -4.53308551e-03,
        2.09932104e-02,  3.13425437e-02,  3.30161117e-02, -4.50995974e-02,
        1.54107008e-02,  5.01369573e-02, -5.96586205e-02,  9.00288206e-03,
       -5.32547645e-02, -6.17159866e-02,  2.41652271e-03, -2.61412840e-02,
        3.61706340e-03,  6.33033961e-02, -8.87479633e-02, -6.23737462e-02,
        2.90604942e-02,  6.97068870e-02, -2.68602092e-02, -1.68619696e-02,
       -1.37926741e-02, -3.07574365e-02,  3.22877243e-02, -3.87897640e-02,
       -3.44157629e-02,  4.28818315e-02, -4.95768292e-03,  5.81265660e-03,
       -4.35050242e-02,  1.81497037e-02, -5.09007797e-02, -8.06726590e-02,
       -4.39512217e-03, -1.63297006e-03, -3.67511399e-02, -7.23477453e-02,
        2.98985094e-02,  4.41829972e-02, -5.40666953e-02, -5.17144538e-02,
        1.89872943e-02,  4.60485369e-02, -5.14353346e-03,  2.72631012e-02,
       -4.06631306e-02, -2.43470427e-02, -6.82264380e-03, -9.17673483e-02,
        2.05311123e-02,  2.09643003e-02, -8.46344512e-03, -6.19416032e-03,
       -4.02429737e-02,  8.36215820e-03, -3.45441140e-02,  1.17812715e-02,
       -4.51653674e-02, -1.13768328e-03,  5.07247709e-02,  2.58255079e-02,
        3.46315131e-02, -2.20023282e-02,  1.49076596e-01,  1.88020151e-02,
        2.23122630e-02, -6.36611134e-03, -1.20408917e-02, -2.10245568e-02,
       -2.56574550e-03, -1.57875065e-02,  3.19045857e-02,  2.24971063e-02,
       -4.24094424e-02,  1.47830294e-02,  5.53040653e-02,  2.37798151e-02,
       -2.30080541e-02,  5.64924441e-02,  1.38072122e-04,  7.27012753e-02,
       -2.23548878e-02, -1.86835956e-02,  5.19804135e-02,  3.06707770e-02,
        4.46908129e-03,  3.05080172e-02,  4.74089123e-02, -2.97417998e-01,
        4.01864275e-02, -1.66238938e-02,  1.17303478e-02,  8.68320465e-03,
        3.10833044e-02,  2.65063122e-02, -4.17584367e-02, -1.67297979e-03,
       -4.18496467e-02,  2.28750296e-02,  6.88194409e-02,  5.99424876e-02,
       -6.01308141e-03, -3.13150436e-02, -3.49089550e-03,  6.38854206e-02,
       -1.55219920e-02,  2.07453128e-02, -6.75014704e-02,  1.38153406e-02,
        5.37333712e-02,  1.80884778e-01,  2.96237180e-03,  2.04259828e-02,
       -2.05924232e-02,  5.12428768e-02, -2.33939700e-02,  3.45522575e-02,
       -3.98799516e-02, -6.00139098e-03,  1.76610239e-03,  5.39524816e-02,
        3.11698439e-03,  3.01595684e-02, -4.14371714e-02, -4.19347659e-02,
        4.06690408e-03,  2.34335084e-02,  2.67553469e-03,  3.78877507e-03,
        9.62381717e-03,  2.75387242e-02, -2.03027986e-02,  4.21361923e-02,
        3.82787995e-02,  4.20959182e-02, -5.94821870e-02, -2.13261116e-02,
        2.37628352e-02,  1.48765855e-02, -2.39848793e-02,  4.16655242e-02,
        1.03938784e-02, -5.11741918e-03,  3.86162065e-02,  3.01962695e-03,
       -4.03557112e-03,  7.07202451e-03, -6.36384264e-02,  3.22685242e-02,
        5.15610687e-02,  7.67554417e-02,  3.93496267e-02,  1.87393744e-02],
      dtype=float32)

In [40]:
df['embedding'] = df['document'].apply(lambda doc : model.encode(doc))

In [41]:
df[['document', 'embedding']].to_csv('Natural_Language_v.csv', index = False)

In [42]:
tf = pd.read_csv('Natural_Language_v.csv')

In [43]:
tf

,document,embedding
0,PAPER ID : 2604.26951v1\n\n Title : Turning t...,[-6.46216422e-02 -3.04427557e-02 -3.88947912e-...
1,PAPER ID : 2604.26231v1\n\n Title : ProMax: E...,[-9.21909325e-03 5.93710877e-02 7.51834537e-...
2,PAPER ID : 2604.26567v1\n\n Title : AirZoo: A...,[-3.92071120e-02 -2.68844105e-02 9.02776234e-...
3,PAPER ID : 2604.26565v1\n\n Title : DenseStep...,[-4.38059233e-02 6.94108289e-03 4.05383622e-...
4,PAPER ID : 2604.26520v1\n\n Title : 3D-LENS: ...,[-2.21086219e-02 7.91376829e-03 -1.02314660e-...
...,...,...
7696,PAPER ID : 2509.23762v3\n\n Title : Accuracy-...,[-1.97270438e-02 -1.60342678e-02 -4.40570638e-...
7697,PAPER ID : 2509.23791v2\n\n Title : CaRe-BN: ...,[-8.41219798e-02 -1.54253212e-03 -2.14015618e-...
7698,PAPER ID : 2509.23896v2\n\n Title : A Computa...,[-9.11315829e-02 -1.45298673e-03 -9.92596336e-...
7699,PAPER ID : 2509.23796v1\n\n Title : From Frus...,[-1.20635174e-01 1.21417679e-02 4.31137979e-...
7700,PAPER ID : 2509.23516v4\n\n Title : Network-O...,[-7.63342008e-02 -1.72049776e-02 -2.11691223e-...